# Generated by Django 4.0.5 on 2022-06-15 11:04

from django.db import migrations, models
import django.utils.timezone
import todoapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['due_date']},
        ),
        migrations.RenameField(
            model_name='todo',
            old_name='Title',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Date',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='Description',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='due_date',
            field=models.DateTimeField(default=todoapp.models.one_week_hence),
        ),
    ]
